from fastapi import APIRouter, HTTPException
from database import get_db_connection
from models import *

router = APIRouter()


@router.post("/api/payments", tags=["Payments"])
def record_payment(payment_data: PaymentCreateRequest):
    """Records a new payment manually (as per project assumptions)."""
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("""
            INSERT INTO payments (member_id, amount, payment_method, status) 
            VALUES (%s, %s, %s, %s);
        """, (payment_data.member_id, payment_data.amount, payment_data.payment_method, payment_data.status))
        conn.commit()
        return {"message": "Payment recorded!"}
    except Exception as e:
        conn.rollback()
        raise HTTPException(status_code=400, detail=str(e))
    finally:
        cursor.close()
        conn.close()


@router.get("/api/payments", response_model=List[AllPaymentsResponse], tags=["Payments"])
def get_all_payments():
    """Admin view: All payments with member names."""
    conn = get_db_connection()
    cursor = conn.cursor()
    query = """
        SELECT p.payment_id, m.first_name || ' ' || m.last_name AS member,
               p.amount, p.payment_date, p.payment_method, p.status
        FROM payments p
        JOIN members m ON p.member_id = m.member_id
        ORDER BY p.payment_date DESC;
    """
    cursor.execute(query)
    data = cursor.fetchall()
    cursor.close()
    conn.close()
    return data


@router.get("/api/members/{member_id}/payments", response_model=List[PaymentResponse], tags=["Payments"])
def get_member_payments(member_id: int):
    """Member view: Their payment history."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT amount, payment_date, payment_method, status FROM payments WHERE member_id = %s ORDER BY payment_date DESC;", (member_id,))
    data = cursor.fetchall()
    cursor.close()
    conn.close()
    return data


@router.get("/api/payments/overdue", response_model=List[AllPaymentsResponse], tags=["Payments"])
def get_overdue_payments():
    """Admin view: Finds payments that are pending or overdue."""
    conn = get_db_connection()
    cursor = conn.cursor()
    query = """
        SELECT p.payment_id, m.first_name || ' ' || m.last_name AS member,
               p.amount, p.payment_date, p.payment_method, p.status
        FROM payments p
        JOIN members m ON p.member_id = m.member_id
        WHERE p.status IN ('pending', 'overdue')
        ORDER BY p.payment_date ASC;
    """
    cursor.execute(query)
    data = cursor.fetchall()
    cursor.close()
    conn.close()
    return data


@router.patch("/api/payments/{payment_id}/mark-paid", tags=["Payments"])
def mark_payment_paid(payment_id: int):
    """Updates a specific payment status to paid (retrieved ID from overdue list)."""
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("UPDATE payments SET status = 'paid' WHERE payment_id = %s;", (payment_id,))
    conn.commit()
    cursor.close()
    conn.close()
    return {"message": f"Payment {payment_id} marked as paid."}


@router.get("/api/payments/revenue-by-method", response_model=List[RevenueByMethod], tags=["Payments"])
def get_revenue_by_method():
    """Groups revenue by payment method (Cash, Bank Transfer)."""
    conn = get_db_connection()
    cursor = conn.cursor()
    query = """
        SELECT payment_method,
               COUNT(*) AS total_transactions,
               SUM(amount) AS total_collected
        FROM payments
        WHERE status = 'paid'
        GROUP BY payment_method;
    """
    cursor.execute(query)
    data = cursor.fetchall()
    cursor.close()
    conn.close()
    return data


@router.get("/api/payments/revenue-by-plan", response_model=List[RevenueByPlan], tags=["Payments"])
def get_revenue_by_plan():
    """Calculates total revenue generated by each membership plan."""
    conn = get_db_connection()
    cursor = conn.cursor()
    query = """
        SELECT mp.plan_name,
               COUNT(m.member_id) AS total_members,
               SUM(p.amount) AS total_revenue
        FROM membership_plans mp
        LEFT JOIN members m ON mp.plan_id = m.plan_id
        LEFT JOIN payments p ON m.member_id = p.member_id AND p.status = 'paid'
        GROUP BY mp.plan_name, mp.plan_id
        ORDER BY total_revenue DESC;
    """
    cursor.execute(query)
    data = cursor.fetchall()
    cursor.close()
    conn.close()
    return data


@router.get("/api/payments/detailed-revenue-by-plan", response_model=List[DetailedRevenueByPlan], tags=["Payments"])
def get_detailed_revenue_by_plan():
    """Advanced analytics: Count, Sum, and Average payments per plan."""
    conn = get_db_connection()
    cursor = conn.cursor()
    query = """
        SELECT mp.plan_name,
               COUNT(p.payment_id) AS total_payments,
               SUM(p.amount) AS total_revenue,
               AVG(p.amount) AS avg_payment
        FROM payments p
        JOIN members m ON p.member_id = m.member_id
        JOIN membership_plans mp ON m.plan_id = mp.plan_id
        WHERE p.status = 'paid'
        GROUP BY mp.plan_name
        ORDER BY total_revenue DESC;
    """
    cursor.execute(query)
    data = cursor.fetchall()
    cursor.close()
    conn.close()
    return data


@router.get("/api/payments/monthly-revenue", response_model=List[MonthlyRevenue], tags=["Payments"])
def get_monthly_revenue():
    """Formats dates to YYYY-MM and groups revenue for charts over last 6 months."""
    conn = get_db_connection()
    cursor = conn.cursor()
    query = """
        SELECT TO_CHAR(payment_date, 'YYYY-MM') AS month, SUM(amount) AS total_revenue
        FROM payments
        WHERE status = 'paid' AND payment_date >= CURRENT_DATE - INTERVAL '6 months'
        GROUP BY TO_CHAR(payment_date, 'YYYY-MM')
        ORDER BY month ASC;
    """
    cursor.execute(query)
    data = cursor.fetchall()
    cursor.close()
    conn.close()
    return data


@router.get("/api/payments/top-payers", response_model=List[TopPayingMember], tags=["Payments"])
def get_top_paying_members():
    """Ranks members by total amount paid."""
    conn = get_db_connection()
    cursor = conn.cursor()
    query = """
        SELECT m.first_name || ' ' || m.last_name AS member,
               SUM(p.amount) AS total_paid,
               COUNT(p.payment_id) AS num_payments
        FROM payments p
        JOIN members m ON p.member_id = m.member_id
        WHERE p.status = 'paid'
        GROUP BY m.member_id, m.first_name, m.last_name
        ORDER BY total_paid DESC;
    """
    cursor.execute(query)
    data = cursor.fetchall()
    cursor.close()
    conn.close()
    return data
